In [1]:
import pandas as pd

In [8]:
df_olympics = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/Olympics-Dataset/refs/heads/master/athletes/bios.csv')

In [9]:
df_olympics.sample(3)
df = df_olympics.copy()

In [10]:
# cleanup full name remove the '•' string
df["name"] = df['Full name'].str.replace('•',' ')
# df[["name", "Full name"]].sample(5)

In [16]:
df.sample(4)

# df.info()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name
39097,Competed in Olympic Games,Male,Jerzy Walerian•Skolimowski,Jerzy•Skolimowski,"9 December 1907 in Łuków, Lubelskie (POL)","12 February 1985 in London, England (GBR)",Poland,39400,150 cm / 59 kg,"AZS Warszawa, Warszawa (POL)",NaN,NaN,NaN,NaN,NaN,NaN,Jerzy Walerian Skolimowski
60793,Competed in Olympic Games,Male,"José Luis ""Pepote""•Ballester Tuliesa",•Pepote,"17 August 1968 in Vinaroz, Castellón (ESP)",NaN,Spain,61232,173 cm / 72 kg,Náutico Pto. Pollensa,NaN,NaN,NaN,NaN,NaN,NaN,"José Luis ""Pepote"" Ballester Tuliesa"
69925,Competed in Olympic Games,Male,Ralph Ernst•Pfersich,Ralph•Pfersich,"18 April 1966 in Treuchtlingen, Bayern (GER)",NaN,Germany,70446,180 cm / 74 kg,"LG VfB/Kickers Stuttgart, Stuttgart (GER)",NaN,NaN,NaN,NaN,NaN,NaN,Ralph Ernst Pfersich
127055,Competed in Olympic Games • Competed in Youth ...,Female,Charity Camile•Williams,Charity•Williams,"20 October 1996 in Toronto, Ontario (CAN)",NaN,Canada,129480,162 cm / 68 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Charity Camile Williams

In [81]:
# split measurements into height_cm and weight_kg

# df.sample()

df[['height_cm', 'weight_kg']] = df["Measurements"].str.split('/', expand=True)

In [132]:
# df[["height_cm", "weight_kg"]].sample(8)
# df[df["height_cm"].notna() & df["weight_kg"].isna()][["name","height_cm", "weight_kg"]].sample(10)

# df[df["weight_kg"].isna()][["name","height_cm", "weight_kg"]]
# df[df["Measurements"].str.split('/').str.len() == 1 & df["Measurements"].str.split('/').str.contains('kg')]

df[df["Measurements"].str.contains("kg") & ~df["Measurements"].str.contains('cm')]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patricia Akosua Offel,120 kg,NaN
289,Competed in Olympic Games,Male,Ángel•Bello,Ángel•Bello,"9 January 1951 in Vigo, Pontevedra (ESP)",13 June 2013,Argentina,290,65 kg,"Tiro Federal de Lomas de Zamora, Lomas de Zamo...",NaN,NaN,NaN,NaN,NaN,NaN,Ángel Bello,65 kg,NaN
290,Competed in Olympic Games,Male,Claudio A.•Pafundi,Claudio•Pafundi,31 January 1962,NaN,Argentina,291,76 kg,"Tiro Federal General José de San Martín, San M...",NaN,NaN,NaN,NaN,NaN,NaN,Claudio A. Pafundi,76 kg,NaN
1128,Competed in Olympic Games,Male,Jeffrey O.•Alleyne,Jeffrey•Alleyne,"25 June 1938 in Bridgetown, Saint Michael (BAR)",NaN,Canada,1135,71 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jeffrey O. Alleyne,71 kg,NaN
1132,Competed in Olympic Games,Male,"Edward ""Ed""•Beattie",Ed•Beattie,"4 February 1934 in Kilsyth, Scotland (GBR)",NaN,Canada,1139,60 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Edward ""Ed"" Beattie",60 kg,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143193,Competed in Olympic Games,Male,Rejepbaý•Rejepow,Rejepbaý•Rejepow,23 February 1992,NaN,Turkmenistan,146829,81 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rejepbaý Rejepow,81 kg,NaN
143225,Competed in Olympic Games,Male,Chen•Po-Jen,Chen•Po-Jen,11 May 1998,NaN,Chinese Taipei,146865,96 kg,NaN,NaN,NaN,NaN,NaN,陳•柏任,Oriental,Chen Po-Jen,96 kg,NaN
143542,Competed in Olympic Games,Female,Nefeli•Papadakis,Nefeli•Papadakis,"2 October 1998 in Chicago, Illinois (USA)",NaN,United States,147195,78 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nefeli Papadakis,78 kg,NaN
143852,Competed in Olympic Games,Male,Kyle Douglas•Dake,Kyle•Dake,"25 February 1991 in Ithaca, New York (USA)",NaN,United States,147508,79 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kyle Douglas Dake,79 kg,NaN
144122,Competed in Olympic Games,Female,Scarleth•Ucelo Marroquín,Scarleth•Ucelo,7 April 2000,NaN,Guatemala,147795,114 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scarleth Ucelo Marroquín,114 kg,NaN

In [133]:
df.iloc[143193,:]

Roles            Competed in Olympic Games
Sex                                   Male
Full name                 Rejepbaý•Rejepow
Used name                 Rejepbaý•Rejepow
Born                      23 February 1992
Died                                   NaN
NOC                           Turkmenistan
athlete_id                          146829
Measurements                         81 kg
Affiliations                           NaN
Nick/petnames                          NaN
Title(s)                               NaN
Other names                            NaN
Nationality                            NaN
Original name                          NaN
Name order                             NaN
name                      Rejepbaý Rejepow
height_cm                            81 kg
weight_kg                              NaN
Name: 143193, dtype: object